@ShoppingCartWebAPI_HostAddress = https://localhost:7073

###
POST {{ShoppingCartWebAPI_HostAddress}}/Cart/AddItemToCart?cartId=1&productId=4


###


DELETE {{ShoppingCartWebAPI_HostAddress}}/Cart/DeleteItemFromCart?cartId=1&productId=1

###

DELETE {{ShoppingCartWebAPI_HostAddress}}/Cart/ClearCart?cartId=1

###

PUT {{ShoppingCartWebAPI_HostAddress}}/Cart/AddCouponToCart?cartId=3&coupomId=1

###

POST {{ShoppingCartWebAPI_HostAddress}}/Cart/Add?userName=KAYO

###

GET {{ShoppingCartWebAPI_HostAddress}}/Cart/CompleteCart?cartId=1